Minor update from ACU Repo
alikehel/activecourses pull request #7
Opened 2023-12-10 23:11 UTC by OmarShawky1

* Renamed OS I to Open Source Programs
* Added DB and OS Courses as per Abdallah's Updated

2023-12-10 23:18 UTC, alikehel requested changes
Just rename the new files to the courses names in lowercase separated by hyphens like the rest of the files (instead of general).

![image](https://github.com/alikehel/activecourses/assets/29659555/233a48cd-2391-4881-818e-816078cb0b9a)

2023-12-11 08:29 UTC, alikehel requested changes
put uw-madison in operating-systems directly and remove the cmu folder.

![image](https://github.com/alikehel/activecourses/assets/29659555/44d3ed56-b628-4f20-a193-1ba36a47295a)

2023-12-11 08:33 UTC, OmarShawky1 commented
Done

2023-12-11 08:35 UTC, alikehel approved these changes

2023-12-11 08:35 UTC, merged